runtime: java21
instance_class: F2

env_variables:
  SPRING_PROFILES_ACTIVE: production
  EXPO_PUBLIC_API_URL: https://ispp-2425-g8.ew.r.appspot.com/

handlers:
# Serve environment variables to the frontend
- url: /env.json
  script: auto
  secure: always

# Serve all API calls to Spring
- url: /api/.*
  script: auto

# Serve all static files with url ending with a file extension
- url: /(.*\..+)$
  static_files: frontend/dist/\1
  upload: frontend/dist/(.*\..+)$

# Catch all handler to index.html
- url: /.*
  static_files: frontend/dist/index.html
  upload: frontend/dist/index.html
