runtime: java21
instance_class: F2

handlers:
# Serve all API calls to Spring
- url: /api/.*
  script: auto

# Serve all static files with url ending with a file extension
- url: /(.*\..+)$
  static_files: frontend/dist/_expo/static/js/web/\1
  upload: frontend/dist/_expo/static/js/web/(.*\..+)$

# Catch all handler to index.html
- url: /.*
  static_files: frontend/dist/index.html
  upload: frontend/dist/index.html


