#JOSE TE ODIO
name: Verify Conventional Commits
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
    types: [opened, reopened, edited, review_requested, synchronize]

jobs:
  check:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: webiny/action-conventional-commits@v1.0.3