name: Deploy to App Engine

on:
  push:
    branches:
      - feat/deploy-setup

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: |
          cd frontend
          echo "EXPO_PUBLIC_API_URL=https://ispp-2425-g8-s3.ew.r.appspot.com" >> .env
          npx expo export -p web

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/125642378529/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'my-service-account@ispp-2425-g8-s3.iam.gserviceaccount.com'

      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v2
        with:
          project_id: 'ispp-2425-g8-s3'
          deliverables: 'app.yml'
          promote: true
          flags: '--quiet'

      - name: Test deployed service
        run: curl "${{ steps.deploy.outputs.version_url }}"
