services:
  - name: backend
    type: web
    env: ubuntu  # Esto obliga a Render a usar un entorno Linux base
    repo: https://github.com/ISPP-G-8/infantem.git
    branch: feat/payment_platform_and_subscription_model
    buildCommand: |
      sudo apt-get update && sudo apt-get install -y openjdk-21-jdk
      ./mvnw clean package -DskipTests
    startCommand: "java -jar target/*.jar"
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: PAYPAL_CLIENT_ID
        sync: false  # Lo defines en Render
      - key: PAYPAL_CLIENT_SECRET
        sync: false  # Lo defines en Render
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-21-openjdk
    plan: free  # Puedes cambiarlo a "starter" si quieres más recursos

  - name: frontend
    type: static
    repo: https://github.com/ISPP-G-8/infantem.git
    branch: feat/payment_platform_and_subscription_model
    buildCommand: "npm install && npm build"
    staticPublishPath: "build" # Usa "build" si es React
    envVars:
      - key: VITE_API_URL
        value: "https://infantem.onrender.com"  # Reemplaza con la URL real de tu backend

