name: Run Tests
on:
  push:
    branches:
      - "main"
      - "develop"
  pull_request:
    branches:
      - "main"
      - "develop"

jobs:
  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: infantem_db
          MYSQL_USER: spring_user
          MYSQL_PASSWORD: StrongPassword123!
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-timeout=5s --health-retries=3

    steps:
      - name: Wait for MySQL to be ready
        run: sleep 15  # Espera inicial para que MySQL se inicie

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Configure environment for Backend
        run: |
          echo "SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/infantem_db" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_USERNAME=spring_user" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_PASSWORD=StrongPassword123!" >> $GITHUB_ENV
          echo "SPRING_PROFILES_ACTIVE=test" >> $GITHUB_ENV

      - name: Run Backend tests
        env:
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
          STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
        run: mvn clean test

  test-frontend:
    name: Test Frontend
    runs-on: ubuntu-latest
    needs: test-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run frontend tests
        working-directory: ./frontend
        env:
          EXPO_PUBLIC_STRIPE_API_KEY: ${{ secrets.EXPO_PUBLIC_STRIPE_API_KEY }}
          EXPO_PUBLIC_API_URL: "http://localhost:8080"
        run: npm test